baseURL: 'https://anelson425.github.io/windsboro-hoa-v2'
languageCode: en-us
title: Windsboro HOA
theme: hoa
params:
  masthead: images/windsboro_masthead.jpg
menu:
  main:
    - name: Links
      url: /links
    - name: HOA
      url: /hoa
    - name: Contacts
      url: /contacts
    - name: About Us
      url: /about_us
    - name: Amenities
      url: /amenities
    - name: Gallery
      url: /gallery
copyright: Windsboro HOA